server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: account-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/account_db}
    username: ${SPRING_DATASOURCE_USERNAME:bank}
    password: ${SPRING_DATASOURCE_PASSWORD:bank}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
